myApp/config/routes.rb
Rails.application.routes.draw do
  resources :v_typeregulators
  resources :v_typephysicalsupports
  resources :v_typelights
  resources :v_typelampposts
  resources :v_typeexecutions
  resources :v_typecommunications
  resources :v_typecommands
  resources :v_typeactiveperiods
  resources :v_type_alarm_panels
  resources :v_type_alarm_lamps
  resources :v_type_alarm_circuits
  resources :v_threshold_types
  resources :v_storagetypes
  resources :v_stateregulators
  resources :vs_light_control_events
  resources :vs_data_pkg_transfer_events
  resources :vs_data_collect_events
  resources :v_ruletypeconditions
  resources :v_reasons
  resources :v_purposes
  resources :v_occurrences
  resources :v_generic_events
  resources :vf_photocell_events
  resources :vf_light_sensor_events
  resources :vf_lampmonitor_events
  resources :vf_lampactuator_events
  resources :vf_generic_sensor_events
  resources :vf_electrical_meter_events
  resources :vf_communication_events
  resources :vf_binary_sensor_events
  resources :vf_basic_events
  resources :v_dynamicoperations
  resources :v_controltypes
  resources :v_clotypes
  resources :v_astroclocks
  resources :v_actions
  resources :v_accounts
  resources :users
  resources :si_sms_lists
  resources :si_rf_communications
  resources :si_regulators
  resources :si_physicaldevpanels
  resources :si_physicaldevlamps
  resources :si_physicaldevlamp_si_physicaldevgateways
  resources :si_physicaldevgateways
  resources :si_physicaldevcircuits
  resources :si_panel_circuit_relays
  resources :si_mqtt_type_alarm_epds
  resources :si_mqtt_type_alarm_aps
  resources :si_mqtt_alarm_epds
  resources :si_mqtt_alarm_aps
  resources :si_general_informations
  resources :si_email_lists
  resources :si_alarm_panels
  resources :si_alarm_panel_ed_logicaldevs
  resources :si_alarm_lamps
  resources :si_alarm_lamp_ed_logicaldevs
  resources :si_alarm_circuits
  resources :si_alarm_circuit_si_physicaldevcircuits
  resources :p_fixedtimecontrols
  resources :p_dynamicoperations
  resources :p_dynamiccontrolelements
  resources :p_controlprogramtypes
  resources :p_activeperiodastroclocks
  resources :p_activeperiodabsolutes
  resources :messages
  resources :l_sensors
  resources :l_lightstates
  resources :l_lightcommands
  resources :f_lampmonitors
  resources :f_lampactuators
  resources :f_functions
  resources :f_electricalmeters
  resources :f_communications
  resources :f_bridges
  resources :f_basics
  resources :es_scenes
  resources :ep_controlprograms
  resources :el_lamptypes
  resources :eg_groups_si_physicaldevcircuits
  resources :eg_groups_panel_ed_logicaldevs
  resources :eg_groups_lamp_ed_logicaldevs
  resources :eg_groups
  resources :ed_logicaldevs_v_actions
  resources :ed_logicaldevs_si_regulators
  resources :ed_logicaldevs do
    collection do
      get :get_monitoring_profile
    end
  end
  resources :ed_logicaldev_vs_light_control_events
  resources :ed_logicaldev_vs_data_pkg_transfer_events
  resources :ed_logicaldev_vs_data_collect_events
  resources :ed_logicaldev_v_generic_events
  resources :ed_logicaldev_vf_photocell_events
  resources :ed_logicaldev_vf_light_sensor_events
  resources :ed_logicaldev_vf_lampmonitor_events
  resources :ed_logicaldev_vf_lampactuator_events
  resources :ed_logicaldev_vf_generic_sensor_events
  resources :ed_logicaldev_vf_electrical_meter_events
  resources :ed_logicaldev_vf_communication_events
  resources :ed_logicaldev_vf_binary_sensor_events
  resources :ed_logicaldev_vf_basic_events
  resources :ed_logicaldev_si_physicaldevpanels
  resources :ed_logicaldev_si_physicaldevlamps
  resources :ed_logicaldev_si_physicaldevgateways
  resources :ed_logicaldev_si_physicaldevcircuits
  resources :ed_logicaldev_eg_groups
  resources :ed_classlogicaldevs_f_functions
  resources :ed_classlogicaldevs
  resources :ec_calendars
  resources :c_rulesconditions
  resources :c_conditionccdays
  resources :c_conditionccdates
  resources :c_calendarrules
  resources :ar_flampactuator_targetlightcommands
  resources :ar_flampactuator_scenes
  resources :ar_flampactuator_lamptypes
  resources :ar_flampactuator_feedbacklightcommands
  resources :ar_flampactuator_defaultscenestates
  resources :ar_flampactuator_defaultlightstates
  resources :ar_flampactuator_calendars
  resources :ar_flampactuator_actuallightstates
  resources :ar_fcommtypes
  resources :ar_fcomm_v_typecommunication2s
  resources :ar_fcomm_v_typecommunication1s
  resources :adesc_flampmonitors
  resources :adesc_flampactuators
  resources :adesc_felectricalmeters
  resources :adesc_fcomms
  resources :adesc_fbridges
  resources :adesc_fbasics
  resources :accounts
  resources :a_flampmonitors
  resources :a_flampmonitor_hists
  resources :a_flampactuators
  resources :a_felectricalmeters
  resources :a_felectricalmeter_hists
  resources :a_fcomms
  resources :a_fbridges
  resources :a_fbasics

end

myApp/app/controllers/ar_fcommtypes_controller.rb
class ArFcommtypesController < ApplicationController
  before_action :set_ar_fcommtype, only: [:show, :edit, :update, :destroy]

  # GET /ar_fcommtypes
  # GET /ar_fcommtypes.json
  def index
    @ar_fcommtypes = ArFcommtype.all
  end

  # GET /ar_fcommtypes/1
  # GET /ar_fcommtypes/1.json
  def show
  end

  # GET /ar_fcommtypes/new
  def new
    @ar_fcommtype = ArFcommtype.new
  end

  # GET /ar_fcommtypes/1/edit
  def edit
  end

  # POST /ar_fcommtypes
  # POST /ar_fcommtypes.json
  def create
    @ar_fcommtype = ArFcommtype.new(ar_fcommtype_params)

    respond_to do |format|
      if @ar_fcommtype.save
        format.html { redirect_to @ar_fcommtype, notice: 'Ar fcommtype was successfully created.' }
        format.json { render :show, status: :created, location: @ar_fcommtype }
      else
        format.html { render :new }
        format.json { render json: @ar_fcommtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ar_fcommtypes/1
  # PATCH/PUT /ar_fcommtypes/1.json
  def update
    respond_to do |format|
      if @ar_fcommtype.update(ar_fcommtype_params)
        format.html { redirect_to @ar_fcommtype, notice: 'Ar fcommtype was successfully updated.' }
        format.json { render :show, status: :ok, location: @ar_fcommtype }
      else
        format.html { render :edit }
        format.json { render json: @ar_fcommtype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ar_fcommtypes/1
  # DELETE /ar_fcommtypes/1.json
  def destroy
    @ar_fcommtype.destroy
    respond_to do |format|
      format.html { redirect_to ar_fcommtypes_url, notice: 'Ar fcommtype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ar_fcommtype
      @ar_fcommtype = ArFcommtype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ar_fcommtype_params
      params.require(:ar_fcommtype).permit(:f_communication_id, :v_typecommunication_id)
    end
end

myApp/app/helpers/ar_fcommtypes_helper.rb
module ArFcommtypesHelper
end

myApp/app/views/ar_fcommtypes/_form.html.erb
<%= form_for(@ar_fcommtype) do |f| %>
  <% if @ar_fcommtype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ar_fcommtype.errors.count, "error") %> prohibited this ar_fcommtype from being saved:</h2>

      <ul>
      <% @ar_fcommtype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :f_communication_id %><br>
    <%= f.text_field :f_communication_id %>
  </div>
  <div class="field">
    <%= f.label :v_typecommunication_id %><br>
    <%= f.text_field :v_typecommunication_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myApp/app/views/ar_fcommtypes/edit.html.erb
<h1>Editing Ar Fcommtype</h1>

<%= render 'form' %>

<%= link_to 'Show', @ar_fcommtype %> |
<%= link_to 'Back', ar_fcommtypes_path %>

myApp/app/views/ar_fcommtypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ar Fcommtypes</h1>

<table>
  <thead>
    <tr>
      <th>F communication</th>
      <th>V typecommunication</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ar_fcommtypes.each do |ar_fcommtype| %>
      <tr>
        <td><%= ar_fcommtype.f_communication %></td>
        <td><%= ar_fcommtype.v_typecommunication %></td>
        <td><%= link_to 'Show', ar_fcommtype %></td>
        <td><%= link_to 'Edit', edit_ar_fcommtype_path(ar_fcommtype) %></td>
        <td><%= link_to 'Destroy', ar_fcommtype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ar fcommtype', new_ar_fcommtype_path %>

myApp/app/views/ar_fcommtypes/new.html.erb
<h1>New Ar Fcommtype</h1>

<%= render 'form' %>

<%= link_to 'Back', ar_fcommtypes_path %>

myApp/app/views/ar_fcommtypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>F communication:</strong>
  <%= @ar_fcommtype.f_communication %>
</p>

<p>
  <strong>V typecommunication:</strong>
  <%= @ar_fcommtype.v_typecommunication %>
</p>

<%= link_to 'Edit', edit_ar_fcommtype_path(@ar_fcommtype) %> |
<%= link_to 'Back', ar_fcommtypes_path %>