myApp/config/routes.rb
Rails.application.routes.draw do
  resources :v_typeregulators
  resources :v_typephysicalsupports
  resources :v_typelights
  resources :v_typelampposts
  resources :v_typeexecutions
  resources :v_typecommunications
  resources :v_typecommands
  resources :v_typeactiveperiods
  resources :v_type_alarm_panels
  resources :v_type_alarm_lamps
  resources :v_type_alarm_circuits
  resources :v_threshold_types
  resources :v_storagetypes
  resources :v_stateregulators
  resources :vs_light_control_events
  resources :vs_data_pkg_transfer_events
  resources :vs_data_collect_events
  resources :v_ruletypeconditions
  resources :v_reasons
  resources :v_purposes
  resources :v_occurrences
  resources :v_generic_events
  resources :vf_photocell_events
  resources :vf_light_sensor_events
  resources :vf_lampmonitor_events
  resources :vf_lampactuator_events
  resources :vf_generic_sensor_events
  resources :vf_electrical_meter_events
  resources :vf_communication_events
  resources :vf_binary_sensor_events
  resources :vf_basic_events
  resources :v_dynamicoperations
  resources :v_controltypes
  resources :v_clotypes
  resources :v_astroclocks
  resources :v_actions
  resources :v_accounts
  resources :users
  resources :si_sms_lists
  resources :si_rf_communications
  resources :si_regulators
  resources :si_physicaldevpanels
  resources :si_physicaldevlamps
  resources :si_physicaldevlamp_si_physicaldevgateways
  resources :si_physicaldevgateways
  resources :si_physicaldevcircuits
  resources :si_panel_circuit_relays
  resources :si_mqtt_type_alarm_epds
  resources :si_mqtt_type_alarm_aps
  resources :si_mqtt_alarm_epds
  resources :si_mqtt_alarm_aps
  resources :si_general_informations
  resources :si_email_lists
  resources :si_alarm_panels
  resources :si_alarm_panel_ed_logicaldevs
  resources :si_alarm_lamps
  resources :si_alarm_lamp_ed_logicaldevs
  resources :si_alarm_circuits
  resources :si_alarm_circuit_si_physicaldevcircuits
  resources :p_fixedtimecontrols
  resources :p_dynamicoperations
  resources :p_dynamiccontrolelements
  resources :p_controlprogramtypes
  resources :p_activeperiodastroclocks
  resources :p_activeperiodabsolutes
  resources :messages
  resources :l_sensors
  resources :l_lightstates
  resources :l_lightcommands
  resources :f_lampmonitors
  resources :f_lampactuators
  resources :f_functions
  resources :f_electricalmeters
  resources :f_communications
  resources :f_bridges
  resources :f_basics
  resources :es_scenes
  resources :ep_controlprograms
  resources :el_lamptypes
  resources :eg_groups_si_physicaldevcircuits
  resources :eg_groups_panel_ed_logicaldevs
  resources :eg_groups_lamp_ed_logicaldevs
  resources :eg_groups
  resources :ed_logicaldevs_v_actions
  resources :ed_logicaldevs_si_regulators
  resources :ed_logicaldevs do
    collection do
      get :get_monitoring_profile
    end
  end
  resources :ed_logicaldev_vs_light_control_events
  resources :ed_logicaldev_vs_data_pkg_transfer_events
  resources :ed_logicaldev_vs_data_collect_events
  resources :ed_logicaldev_v_generic_events
  resources :ed_logicaldev_vf_photocell_events
  resources :ed_logicaldev_vf_light_sensor_events
  resources :ed_logicaldev_vf_lampmonitor_events
  resources :ed_logicaldev_vf_lampactuator_events
  resources :ed_logicaldev_vf_generic_sensor_events
  resources :ed_logicaldev_vf_electrical_meter_events
  resources :ed_logicaldev_vf_communication_events
  resources :ed_logicaldev_vf_binary_sensor_events
  resources :ed_logicaldev_vf_basic_events
  resources :ed_logicaldev_si_physicaldevpanels
  resources :ed_logicaldev_si_physicaldevlamps
  resources :ed_logicaldev_si_physicaldevgateways
  resources :ed_logicaldev_si_physicaldevcircuits
  resources :ed_logicaldev_eg_groups
  resources :ed_classlogicaldevs_f_functions
  resources :ed_classlogicaldevs
  resources :ec_calendars
  resources :c_rulesconditions
  resources :c_conditionccdays
  resources :c_conditionccdates
  resources :c_calendarrules
  resources :ar_flampactuator_targetlightcommands
  resources :ar_flampactuator_scenes
  resources :ar_flampactuator_lamptypes
  resources :ar_flampactuator_feedbacklightcommands
  resources :ar_flampactuator_defaultscenestates
  resources :ar_flampactuator_defaultlightstates
  resources :ar_flampactuator_calendars
  resources :ar_flampactuator_actuallightstates
  resources :ar_fcommtypes
  resources :ar_fcomm_v_typecommunication2s
  resources :ar_fcomm_v_typecommunication1s
  resources :adesc_flampmonitors
  resources :adesc_flampactuators
  resources :adesc_felectricalmeters
  resources :adesc_fcomms
  resources :adesc_fbridges
  resources :adesc_fbasics
  resources :accounts
  resources :a_flampmonitors
  resources :a_flampmonitor_hists
  resources :a_flampactuators
  resources :a_felectricalmeters
  resources :a_felectricalmeter_hists
  resources :a_fcomms
  resources :a_fbridges
  resources :a_fbasics

end

myApp/app/models/v_typecommand.rb
class VTypecommand < ActiveRecord::Base
end

myApp/app/controllers/v_typecommands_controller.rb
class VTypecommandsController < ApplicationController
  before_action :set_v_typecommand, only: [:show, :edit, :update, :destroy]

  # GET /v_typecommands
  # GET /v_typecommands.json
  def index
    @v_typecommands = VTypecommand.all
  end

  # GET /v_typecommands/1
  # GET /v_typecommands/1.json
  def show
  end

  # GET /v_typecommands/new
  def new
    @v_typecommand = VTypecommand.new
  end

  # GET /v_typecommands/1/edit
  def edit
  end

  # POST /v_typecommands
  # POST /v_typecommands.json
  def create
    @v_typecommand = VTypecommand.new(v_typecommand_params)

    respond_to do |format|
      if @v_typecommand.save
        format.html { redirect_to @v_typecommand, notice: 'V typecommand was successfully created.' }
        format.json { render :show, status: :created, location: @v_typecommand }
      else
        format.html { render :new }
        format.json { render json: @v_typecommand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /v_typecommands/1
  # PATCH/PUT /v_typecommands/1.json
  def update
    respond_to do |format|
      if @v_typecommand.update(v_typecommand_params)
        format.html { redirect_to @v_typecommand, notice: 'V typecommand was successfully updated.' }
        format.json { render :show, status: :ok, location: @v_typecommand }
      else
        format.html { render :edit }
        format.json { render json: @v_typecommand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /v_typecommands/1
  # DELETE /v_typecommands/1.json
  def destroy
    @v_typecommand.destroy
    respond_to do |format|
      format.html { redirect_to v_typecommands_url, notice: 'V typecommand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_v_typecommand
      @v_typecommand = VTypecommand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def v_typecommand_params
      params.require(:v_typecommand).permit(:name, :short_name)
    end
end

myApp/app/helpers/v_typecommands_helper.rb
module VTypecommandsHelper
end

myApp/app/views/v_typecommands/_form.html.erb
<%= form_for(@v_typecommand) do |f| %>
  <% if @v_typecommand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@v_typecommand.errors.count, "error") %> prohibited this v_typecommand from being saved:</h2>

      <ul>
      <% @v_typecommand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br>
    <%= f.text_area :short_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myApp/app/views/v_typecommands/edit.html.erb
<h1>Editing V Typecommand</h1>

<%= render 'form' %>

<%= link_to 'Show', @v_typecommand %> |
<%= link_to 'Back', v_typecommands_path %>

myApp/app/views/v_typecommands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing V Typecommands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @v_typecommands.each do |v_typecommand| %>
      <tr>
        <td><%= v_typecommand.name %></td>
        <td><%= v_typecommand.short_name %></td>
        <td><%= link_to 'Show', v_typecommand %></td>
        <td><%= link_to 'Edit', edit_v_typecommand_path(v_typecommand) %></td>
        <td><%= link_to 'Destroy', v_typecommand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New V typecommand', new_v_typecommand_path %>

myApp/app/views/v_typecommands/new.html.erb
<h1>New V Typecommand</h1>

<%= render 'form' %>

<%= link_to 'Back', v_typecommands_path %>

myApp/app/views/v_typecommands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @v_typecommand.name %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @v_typecommand.short_name %>
</p>

<%= link_to 'Edit', edit_v_typecommand_path(@v_typecommand) %> |
<%= link_to 'Back', v_typecommands_path %>