myApp/config/routes.rb
Rails.application.routes.draw do
  resources :v_typeregulators
  resources :v_typephysicalsupports
  resources :v_typelights
  resources :v_typelampposts
  resources :v_typeexecutions
  resources :v_typecommunications
  resources :v_typecommands
  resources :v_typeactiveperiods
  resources :v_type_alarm_panels
  resources :v_type_alarm_lamps
  resources :v_type_alarm_circuits
  resources :v_threshold_types
  resources :v_storagetypes
  resources :v_stateregulators
  resources :vs_light_control_events
  resources :vs_data_pkg_transfer_events
  resources :vs_data_collect_events
  resources :v_ruletypeconditions
  resources :v_reasons
  resources :v_purposes
  resources :v_occurrences
  resources :v_generic_events
  resources :vf_photocell_events
  resources :vf_light_sensor_events
  resources :vf_lampmonitor_events
  resources :vf_lampactuator_events
  resources :vf_generic_sensor_events
  resources :vf_electrical_meter_events
  resources :vf_communication_events
  resources :vf_binary_sensor_events
  resources :vf_basic_events
  resources :v_dynamicoperations
  resources :v_controltypes
  resources :v_clotypes
  resources :v_astroclocks
  resources :v_actions
  resources :v_accounts
  resources :users
  resources :si_sms_lists
  resources :si_rf_communications
  resources :si_regulators
  resources :si_physicaldevpanels
  resources :si_physicaldevlamps
  resources :si_physicaldevlamp_si_physicaldevgateways
  resources :si_physicaldevgateways
  resources :si_physicaldevcircuits
  resources :si_panel_circuit_relays
  resources :si_mqtt_type_alarm_epds
  resources :si_mqtt_type_alarm_aps
  resources :si_mqtt_alarm_epds
  resources :si_mqtt_alarm_aps
  resources :si_general_informations
  resources :si_email_lists
  resources :si_alarm_panels
  resources :si_alarm_panel_ed_logicaldevs
  resources :si_alarm_lamps
  resources :si_alarm_lamp_ed_logicaldevs
  resources :si_alarm_circuits
  resources :si_alarm_circuit_si_physicaldevcircuits
  resources :p_fixedtimecontrols
  resources :p_dynamicoperations
  resources :p_dynamiccontrolelements
  resources :p_controlprogramtypes
  resources :p_activeperiodastroclocks
  resources :p_activeperiodabsolutes
  resources :messages
  resources :l_sensors
  resources :l_lightstates
  resources :l_lightcommands
  resources :f_lampmonitors
  resources :f_lampactuators
  resources :f_functions
  resources :f_electricalmeters
  resources :f_communications
  resources :f_bridges
  resources :f_basics
  resources :es_scenes
  resources :ep_controlprograms
  resources :el_lamptypes
  resources :eg_groups_si_physicaldevcircuits
  resources :eg_groups_panel_ed_logicaldevs
  resources :eg_groups_lamp_ed_logicaldevs
  resources :eg_groups
  resources :ed_logicaldevs_v_actions
  resources :ed_logicaldevs_si_regulators
  resources :ed_logicaldevs do
    collection do
      get :get_monitoring_profile
    end
  end
  resources :ed_logicaldev_vs_light_control_events
  resources :ed_logicaldev_vs_data_pkg_transfer_events
  resources :ed_logicaldev_vs_data_collect_events
  resources :ed_logicaldev_v_generic_events
  resources :ed_logicaldev_vf_photocell_events
  resources :ed_logicaldev_vf_light_sensor_events
  resources :ed_logicaldev_vf_lampmonitor_events
  resources :ed_logicaldev_vf_lampactuator_events
  resources :ed_logicaldev_vf_generic_sensor_events
  resources :ed_logicaldev_vf_electrical_meter_events
  resources :ed_logicaldev_vf_communication_events
  resources :ed_logicaldev_vf_binary_sensor_events
  resources :ed_logicaldev_vf_basic_events
  resources :ed_logicaldev_si_physicaldevpanels
  resources :ed_logicaldev_si_physicaldevlamps
  resources :ed_logicaldev_si_physicaldevgateways
  resources :ed_logicaldev_si_physicaldevcircuits
  resources :ed_logicaldev_eg_groups
  resources :ed_classlogicaldevs_f_functions
  resources :ed_classlogicaldevs
  resources :ec_calendars
  resources :c_rulesconditions
  resources :c_conditionccdays
  resources :c_conditionccdates
  resources :c_calendarrules
  resources :ar_flampactuator_targetlightcommands
  resources :ar_flampactuator_scenes
  resources :ar_flampactuator_lamptypes
  resources :ar_flampactuator_feedbacklightcommands
  resources :ar_flampactuator_defaultscenestates
  resources :ar_flampactuator_defaultlightstates
  resources :ar_flampactuator_calendars
  resources :ar_flampactuator_actuallightstates
  resources :ar_fcommtypes
  resources :ar_fcomm_v_typecommunication2s
  resources :ar_fcomm_v_typecommunication1s
  resources :adesc_flampmonitors
  resources :adesc_flampactuators
  resources :adesc_felectricalmeters
  resources :adesc_fcomms
  resources :adesc_fbridges
  resources :adesc_fbasics
  resources :accounts
  resources :a_flampmonitors
  resources :a_flampmonitor_hists
  resources :a_flampactuators
  resources :a_felectricalmeters
  resources :a_felectricalmeter_hists
  resources :a_fcomms
  resources :a_fbridges
  resources :a_fbasics

end

myApp/app/models/ed_logicaldev_si_physicaldevlamp.rb
class EdLogicaldevSiPhysicaldevlamp < ActiveRecord::Base
  belongs_to :ed_logicaldev
  belongs_to :si_physicaldevlamp
end

myApp/app/controllers/ed_logicaldev_si_physicaldevlamps_controller.rb
class EdLogicaldevSiPhysicaldevlampsController < ApplicationController
  before_action :set_ed_logicaldev_si_physicaldevlamp, only: [:show, :edit, :update, :destroy]

  # GET /ed_logicaldev_si_physicaldevlamps
  # GET /ed_logicaldev_si_physicaldevlamps.json
  def index
    @ed_logicaldev_si_physicaldevlamps = EdLogicaldevSiPhysicaldevlamp.all
  end

  # GET /ed_logicaldev_si_physicaldevlamps/1
  # GET /ed_logicaldev_si_physicaldevlamps/1.json
  def show
  end

  # GET /ed_logicaldev_si_physicaldevlamps/new
  def new
    @ed_logicaldev_si_physicaldevlamp = EdLogicaldevSiPhysicaldevlamp.new
  end

  # GET /ed_logicaldev_si_physicaldevlamps/1/edit
  def edit
  end

  # POST /ed_logicaldev_si_physicaldevlamps
  # POST /ed_logicaldev_si_physicaldevlamps.json
  def create
    @ed_logicaldev_si_physicaldevlamp = EdLogicaldevSiPhysicaldevlamp.new(ed_logicaldev_si_physicaldevlamp_params)

    respond_to do |format|
      if @ed_logicaldev_si_physicaldevlamp.save
        format.html { redirect_to @ed_logicaldev_si_physicaldevlamp, notice: 'Ed logicaldev si physicaldevlamp was successfully created.' }
        format.json { render :show, status: :created, location: @ed_logicaldev_si_physicaldevlamp }
      else
        format.html { render :new }
        format.json { render json: @ed_logicaldev_si_physicaldevlamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ed_logicaldev_si_physicaldevlamps/1
  # PATCH/PUT /ed_logicaldev_si_physicaldevlamps/1.json
  def update
    respond_to do |format|
      if @ed_logicaldev_si_physicaldevlamp.update(ed_logicaldev_si_physicaldevlamp_params)
        format.html { redirect_to @ed_logicaldev_si_physicaldevlamp, notice: 'Ed logicaldev si physicaldevlamp was successfully updated.' }
        format.json { render :show, status: :ok, location: @ed_logicaldev_si_physicaldevlamp }
      else
        format.html { render :edit }
        format.json { render json: @ed_logicaldev_si_physicaldevlamp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ed_logicaldev_si_physicaldevlamps/1
  # DELETE /ed_logicaldev_si_physicaldevlamps/1.json
  def destroy
    @ed_logicaldev_si_physicaldevlamp.destroy
    respond_to do |format|
      format.html { redirect_to ed_logicaldev_si_physicaldevlamps_url, notice: 'Ed logicaldev si physicaldevlamp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ed_logicaldev_si_physicaldevlamp
      @ed_logicaldev_si_physicaldevlamp = EdLogicaldevSiPhysicaldevlamp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ed_logicaldev_si_physicaldevlamp_params
      params.require(:ed_logicaldev_si_physicaldevlamp).permit(:ed_logicaldev_id, :si_physicaldevlamp_id)
    end
end

myApp/app/helpers/ed_logicaldev_si_physicaldevlamps_helper.rb
module EdLogicaldevSiPhysicaldevlampsHelper
end

myApp/app/views/ed_logicaldev_si_physicaldevlamps/_form.html.erb
<%= form_for(@ed_logicaldev_si_physicaldevlamp) do |f| %>
  <% if @ed_logicaldev_si_physicaldevlamp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ed_logicaldev_si_physicaldevlamp.errors.count, "error") %> prohibited this ed_logicaldev_si_physicaldevlamp from being saved:</h2>

      <ul>
      <% @ed_logicaldev_si_physicaldevlamp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ed_logicaldev_id %><br>
    <%= f.text_field :ed_logicaldev_id %>
  </div>
  <div class="field">
    <%= f.label :si_physicaldevlamp_id %><br>
    <%= f.text_field :si_physicaldevlamp_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

myApp/app/views/ed_logicaldev_si_physicaldevlamps/edit.html.erb
<h1>Editing Ed Logicaldev Si Physicaldevlamp</h1>

<%= render 'form' %>

<%= link_to 'Show', @ed_logicaldev_si_physicaldevlamp %> |
<%= link_to 'Back', ed_logicaldev_si_physicaldevlamps_path %>

myApp/app/views/ed_logicaldev_si_physicaldevlamps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ed Logicaldev Si Physicaldevlamps</h1>

<table>
  <thead>
    <tr>
      <th>Ed logicaldev</th>
      <th>Si physicaldevlamp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ed_logicaldev_si_physicaldevlamps.each do |ed_logicaldev_si_physicaldevlamp| %>
      <tr>
        <td><%= ed_logicaldev_si_physicaldevlamp.ed_logicaldev %></td>
        <td><%= ed_logicaldev_si_physicaldevlamp.si_physicaldevlamp %></td>
        <td><%= link_to 'Show', ed_logicaldev_si_physicaldevlamp %></td>
        <td><%= link_to 'Edit', edit_ed_logicaldev_si_physicaldevlamp_path(ed_logicaldev_si_physicaldevlamp) %></td>
        <td><%= link_to 'Destroy', ed_logicaldev_si_physicaldevlamp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ed logicaldev si physicaldevlamp', new_ed_logicaldev_si_physicaldevlamp_path %>

myApp/app/views/ed_logicaldev_si_physicaldevlamps/new.html.erb
<h1>New Ed Logicaldev Si Physicaldevlamp</h1>

<%= render 'form' %>

<%= link_to 'Back', ed_logicaldev_si_physicaldevlamps_path %>

myApp/app/views/ed_logicaldev_si_physicaldevlamps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ed logicaldev:</strong>
  <%= @ed_logicaldev_si_physicaldevlamp.ed_logicaldev %>
</p>

<p>
  <strong>Si physicaldevlamp:</strong>
  <%= @ed_logicaldev_si_physicaldevlamp.si_physicaldevlamp %>
</p>

<%= link_to 'Edit', edit_ed_logicaldev_si_physicaldevlamp_path(@ed_logicaldev_si_physicaldevlamp) %> |
<%= link_to 'Back', ed_logicaldev_si_physicaldevlamps_path %>